### ISSUE TITLE
[CleanRepo] remove-hops command appears to expect a certain directory structure

### ISSUE THREAD

**Issue by Mikejo5000** [dotnet/docs-tools#349]
@gewarren Testing the remove-hops feature to fix potential daisy chains in VS repo. Ran into an error... included the commands here (command line version of tool).

C:\git-repos\docs-tools\cleanrepo\CleanRepo\bin\release\net8>CleanRepo.exe --remove-hops --articles-directory c:\git-repos\visualstudio-docs-pr/docs

Enter the URL base path for this docset, for example, '/dotnet' or '/windows/uwp':

/visualstudio

Enter the path to the directory that contains the docfx.json file:

c:\git-repos\visualstudio-docs-pr\docs

Removing hops from the '.openpublishing.redirection.json' redirection file.
Caught exception while reading the c:\git-repos\visualstudio-docs-pr\.openpublishing.redirection.json file: The JSON value could not be converted to System.Nullable`1[System.Boolean]. Path: $.redirections[0].redirect_document_id | LineNumber: 5 | BytePositionInLine: 37. Cannot get the value of a token type 'String' as a boolean.
Deserialization of redirection file failed.

Removing hops from the '.openpublishing.redirection.mac.json' redirection file.

Removing hops from the '.openpublishing.redirection.subscriptions.json' redirection file.

Removing hops from the '.openpublishing.redirection.vs2017.json' redirection file.
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: c:\git-repos\visualstudio-docs-pr\docs\vsto\accessibility-in-office-projects.md
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at CleanRepo.DocFxRepo.RemoveRedirectHopsFromFile(FileInfo redirectsFile, Dictionary`2 docsets, String rootPath)in C:\git-repos\docs-tools\cleanrepo\CleanRepo\Repo.cs:line 636
   at CleanRepo.DocFxRepo.RemoveAllRedirectHops() in C:\git-repos\docs-tools\cleanrepo\CleanRepo\Repo.cs:line 565
   at CleanRepo.Program.RunOptions(Options options) in C:\git-repos\docs-tools\cleanrepo\CleanRepo\Program.cs:line 402
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at CleanRepo.Program.Main(String[] args) in C:\git-repos\docs-tools\cleanrepo\CleanRepo\Program.cs:line 36

**Comment by gewarren** [comment]
@Mikejo5000 This is happening because you have two redirects for the same file:

1. https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/f6dc881f5b4fa8a7300d27cefaa0a6d53303b5ba/.openpublishing.redirection.vs2017.json#L39585
2. https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/f6dc881f5b4fa8a7300d27cefaa0a6d53303b5ba/.openpublishing.redirection.vs2017.json#L42686

One could argue that CleanRepo should handle it better though, so I'll leave this issue open. But you could remove one of those redirects for now and then rerun the tool.

**Comment by Mikejo5000** [comment]
@gewarren Great, thanks! I'll try it out

**Comment by Mikejo5000** [comment]
@gewarren Genevieve, do you know what this error means? I don't see anything wrong with line 905 in the redirection file.

Removing hops from the '.openpublishing.redirection.json' redirection file.
Caught exception while reading the C:\git-repos\visualstudio-docs-pr\.openpublishing.redirection.json file: The JSON value could not be converted to System.Nullable`1[System.Boolean]. Path: $.redirections[180].redirect_document_id | LineNumber: 905 | BytePositionInLine: 37. Cannot get the value of a token type 'String' as a boolean.
Deserialization of redirection file failed.

**Comment by gewarren** [comment]
@Mikejo5000 Probably means you have true or false in quotes. Should look like this instead: https://github.com/dotnet/docs/blob/b74766942f2d9c52375d29c515be9fdcaced4d4b/.openpublishing.redirection.csharp.json#L230

**Comment by Mikejo5000** [comment]
Yes, that looks right. Thanks!

**Comment by Mikejo5000** [comment]
It appears that the tool is not handling monikered redirects well. The following causes a "same key" error when there's another redirect with the same source_path but a different moniker value (vs-2022):
    {
      "source_path": "docs/install/visual-studio-build-numbers-and-release-dates.md",
      "redirect_url": "/visualstudio/releases/2019/history#release-dates-and-build-numbers",
      "redirect_document_id": false,
      "monikers": [
        "vs-2019"
    ]
    },

**Comment by gewarren** [comment]
@Mikejo5000 Okay, thank you. Let's track that with this issue. I'll update the title.
